### ISSUE TITLE
severe sql injection, giving superuser access to anyone

### ISSUE THREAD

**Issue by srihari-humbarwadi** [omkar2403/inout#1]
Srihari Humbarwadi -
```
$query="SELECT * FROM log WHERE user='$user' AND pass='$pass'
```
can easily bypass this credential check with a tautology based sqli

**Comment by omkar2403** [comment]
Thank you for your suggestion. Its worth. I would definitely work for it.

**Comment by omkar2403** [comment]
Security Update has Pushed.
